### ISSUE TITLE
What does dynamiclua do differently that the debug functionality is supported?

### ISSUE THREAD

**Issue by pixelport** [nrother/dynamiclua#18]
The Project description says that dynamiclua is a Wrapper for NLua.
But NLua doesn't support debug functionality at all.
What does dynamiclua do differently that the debug functionality is supported?

Nice Project! Keep it up!

**Comment by nrother** [comment]
I don't quite understand what you mean.. In fact NLua supports debugging through `SetDebugHook()` and DynamicLua not :smile:  , because these functions are not visible through the wrapper. (I never needed them).

Maybe you mean something different? As far as I can remember I have not done something special to support the debugging of Lua scripts with DynamicLua.

**Comment by pixelport** [comment]
I am so sorry, I mixed up NLua and NeoLua. :smile:
